behaviors:
  Agent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 25600
      learning_rate: 0.0003
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.3
        gamma: 0.9
        demo_path: Assets/Demonstrations/NewTry.demo
        encoding_size: 64
        use_actions: true
    behavioral_cloning:
      strength: 0.1
      demo_path: Assets/Demonstrations/NewTry.demo
    time_horizon: 64
    max_steps: 6000000
    summary_freq: 50000
