behaviors:
  Agent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 25600
      learning_rate: 0.00005
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.5
        gamma: 0.9
        demo_path: Assets/Demonstrations/NewDan.demo
        encoding_size: 64
        use_actions: true
    behavioral_cloning:
      strength: 0.5
      demo_path: Assets/Demonstrations/NewDan.demo
    time_horizon: 64
    max_steps: 10000000
    summary_freq: 50000
    #self_play:
    #    window: 10
    #    play_against_latest_model_ratio: 0.5
    #    save_steps: 20000
    #    swap_steps: 10000
    #    team_change: 100000